apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ClusterCurator
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: local-cluster
  namespace: local-cluster
spec:
  desiredCuration: upgrade
  destroy:
    jobMonitorTimeout: 5
  install:
    jobMonitorTimeout: 5
  scale:
    jobMonitorTimeout: 5
  upgrade:
    desiredUpdate: 4.15.40
    monitorTimeout: 120
